### PR TITLE
IE 11 compatibility, use Selection.collapse/extend instead of Selection.setBaseAndExtent

### LINKED ISSUE #1385: IE 11 compatibility
#### Do you want to request a *feature* or report a *bug*?
bug

#### What's the current behavior?

If you try to use the editor with IE 11, the editor crashes 

```
TypeError: Object doesn't support property or method 'setBaseAndExtent'
   at n.updateSelection (http://slatejs.org/build.prod.js:4994:3878)
   at n.componentDidUpdate (http://slatejs.org/build.prod.js:4994:3021)
   at commitLifeCycles (http://slatejs.org/build.prod.js:4807:27707)
   at n (http://slatejs.org/build.prod.js:4807:31678)
   at u (http://slatejs.org/build.prod.js:4808:1303)
   at c (http://slatejs.org/build.prod.js:4808:1793)
   at batchedUpdates (http://slatejs.org/build.prod.js:4808:4655)
   at qb (http://slatejs.org/build.prod.js:4807:3872)
   at ob (http://slatejs.org/build.prod.js:4807:3806)
   at sb.batchedUpdates (http://slatejs.org/build.prod.js:4808:19675)
```

#### What's the expected behavior?

The editor should not crash.

this compatibility issue have been introduced by #1354

IE11 does not support the Selection.setBaseAndExtent function
pull request is on the way

### PR DESCRIPTION
**Pull request by illesg**
fixes #1385  
by using Selection.collapse/extend, we can preserve the backward/forward selection direction, and they are supported on IE 11

EDIT: Selection.extend is not available in IE11...

### CODE REVIEW

**Comment by lxcid** [comment]
This fix is awesome, though I was wondering if we should conditional switch the path based on browser?

**Comment by illesg** [comment]
Thank you :), 
I don't think we should, it works in the other browsers too, so I think it's simpler this way

**Comment by illesg** [comment]
i just noticed that the backward selection through spans is buggy again, but in a different way than before: 
selection-bug

i will look into it today

**Comment by isubastiCadmus** [comment]
@illesg might want to try putting the addRange inside the else statement of isBackward and see how it goes?

**Comment by illesg** [comment]
@isubastiCadmus yes, you're right, addRange is the problem
i went with the Selection.collapse/extend for both condition solution, it seems it works with all browsers, thanks

**Comment by isubastiCadmus** [comment]
@illesg no problem. It was kinda my bad as well putting a fix with setBaseAndExtend as I forgot that it's not available in all browser

**Comment by illesg** [comment]
ok it's weird, it looks like IE does not need the selection restoration at all, (and doesn't support the Selection.extend either) 
and by the way there was another bug in the current implementation with Chrome and Safari:
selection-bug-2

i fixed it by checking the selection direction, and the focusNode
let me know if there is a problem with this implementation, i'm pretty new here

File: packages/slate-react/src/components/content.js [hunk 1]
```diff
@@ -192,14 +197,23 @@ class Content extends React.Component {
...
+      // COMPAT: Since the DOM range has no concept of backwards/forwards
+      // we need to check and do the right thing here.
+      if (isBackward) {
+        native.collapse(range.endContainer, range.endOffset)
+        native.extend(range.startContainer, range.startOffset)
+      } else {
+        native.collapse(range.startContainer, range.startOffset)
+        native.extend(range.endContainer, range.endOffset)
+      }
+    } else if (selection.isCollapsed) {
```
Comment (ianstormtaylor) [inline packages/slate-react/src/components/content.js]: I'm not sure about this check, because won't this mean that in IE11 when the selection is expanded we won't be updating it at all? This seems like it won't handle programmatic selection changes that result in an expanded selection.

File: packages/slate-react/src/components/content.js [hunk 2]
```diff
@@ -175,11 +175,16 @@ class Content extends React.Component {
     if (current) {
       if (
         (
+          !isBackward &&
+          focusNode == current.startContainer &&
```
Comment (ianstormtaylor) [inline packages/slate-react/src/components/content.js]: What was the need for these updates to these conditionals? The added `isBackward` check makes sense to me, and seems like a smart improvement. The other one I'm not sure I understand.

Comment (illesg) [reply packages/slate-react/src/components/content.js]: Sorry, i messed up that part, i thought it's a bug, but it isn't, the native textarea works the same way:



select text backward by clicking on a text, and select with shift+click, and continue the selection with shift + right arrow

I will clean it up today

File: packages/slate-react/src/components/content.js (hunk 1 above)
Comment (illesg) [reply packages/slate-react/src/components/content.js]: it's because I introduced a weird bug in IE with the previous change (by checking the direction and the focus node, it's not necessary anymore) 
change is on the way

**Comment by ianstormtaylor** [comment]
Thanks @illesg looks good!

**Comment by lxcid** [comment]
@illesg, this broke Firefox on my side though. This is an old bug. The previous implementation actually fixed it.

In my implementation, I had multiple `<Editor />`, when user press the up arrow, I'll unselect the current one and select the previous one. This cause firefox to just crash. The crash log shows the following:

screenshot 2017-11-17 15 01 43

I'll try to replicate it in jsfilddle and open a new issue regarding this.
