### PR TITLE
fix(scroll-to-selection): use getClientRects when selectionRect.top/height is still 0 in Safari

### LINKED ISSUE #1445: Editor scrolls on every newline when inside a scrollable container in Safari
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

when you press enter and there's no text following up (aka newline), the scroll jumps around in Safari.

related with #1416 #1428 

@erquhart will use your fiddle since it still serves it's purpose, hope you don't mind.
https://jsfiddle.net/fj9dvhom/6/

GIF

Sorry for the GIF quality.

I shall push a PR after this.

#### What's the expected behavior?

no jumping.

### PR DESCRIPTION
**Pull request by zGrav**
Tested on Safari 11.0.1 on OS X 10.13.1 with a scrollable container.

Fixes #1445 .

### CODE REVIEW

**Comment by zGrav** [comment]
Apologies for so many commits, I finally figured out how to do the eslint test with yarn, took me a bit longer than expected 😢

File: packages/slate-react/src/utils/scroll-to-selection.js [hunk 1]
```diff
@@ -80,6 +80,10 @@ function scrollToSelection(selection) {
     }
 
     selectionRect = range.getBoundingClientRect()
+
+    if (selectionRect.top == 0 && selectionRect.height == 0) {
```
Comment (maddrag0n) [inline packages/slate-react/src/utils/scroll-to-selection.js]: `if (selectionRect.top === 0 && selectionRect.height === 0)`

File: packages/slate-react/src/utils/scroll-to-selection.js [hunk 2]
```diff
@@ -80,6 +80,10 @@ function scrollToSelection(selection) {
...
+      selectionRect = range.getClientRects()[0]
```
Comment (maddrag0n) [inline packages/slate-react/src/utils/scroll-to-selection.js]:
```
if (range && range.getClientRects && range.getClientRects().length) {
    selectionRect = range.getClientRects()[0]
}
```

Comment (zGrav) [reply packages/slate-react/src/utils/scroll-to-selection.js]: merci <3

File: packages/slate-react/src/utils/scroll-to-selection.js (hunk 1 above)
Comment (maddrag0n) [reply packages/slate-react/src/utils/scroll-to-selection.js]: as slate apparently uses improper `==` checks  throughout the code base... ignore this maybe?

**Comment by lxcid** [comment]
In my own codebase I use this check though, is this alternative suggestion also solve the issue?

```js
    const selection = window.getSelection();
    let range = selection.getRangeAt(0);
    if (IS_SAFARI) {
      // `getBoundingClientRect` is buggy on Safari when there is no selected text active.
      // A workaround is available at https://stackoverflow.com/a/44261188
      range = range.cloneRange();
      range.setStart(range.startContainer, 0);
    }
```

**Comment by lxcid** [comment]
`IS_SAFARI` is available in `src/contants/environment.js`

**Comment by zGrav** [comment]
@lxcid , I believe I tried the cloneRange and it wasn’t working as intended, my implementation does work for empty text and keeps the original implementation in place when there is text.

I did not know about IS_SAFARI thanks!

**Comment by lxcid** [comment]
I see! Good to know of alternative solution!

**Comment by ianstormtaylor** [comment]
Thanks @zGrav!
