### PR TITLE
Prevent history mutation during initialization

### LINKED ISSUE #1327: Losing redo state after popping last undo item
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
https://jsfiddle.net/doodlewind/6ofmL42m/

1. Select some texts and click `delete`, repeat several times to fill history stack.
2. Click `undo`, begin traveling in history states.
3. When `undos.size == 1`, click `undo`, **redo count is cleared!**

During traveling in history, `undos.size` + `redos.size` is an constant. But **when user wants to pop up last undo item, redo stack is cleared**. In this case user can't travel back with `redo`, bringing disturbing UE.

bug-lose-redo

#### What's the expected behavior?
When `undos.size == 1`, popping up last undo item shouldn't clear the redo stack.

I've fixed this in my local branch, a PR is landing soon!

### LINKED ISSUE #1328: Wrong undo count after initialization
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
https://jsfiddle.net/doodlewind/6ofmL42m/

Open this page and do nothing, `undos.size` is 1 instead of 0. Neither can we popped up this undo item. As a result, it leads to inaccurate computing of `state.hasUndos`.

#### What's the expected behavior?
1. `undos.size` should be 0 as an init state.
2. Last undo item should be able to popped up.

I've fixed this in my local branch, a PR is landing soon!

### PR DESCRIPTION
**Pull request by doodlewind**
Fixes #1327 
Fixes #1328 

Currently there are two weird history stack behaviors:

1. When popping up last undo item, redo stack is cleared.
2. After initialization, `undos.size` is 1 instead of 0.

According to existing comments, during initialization, `editor.schema` will change once, then `onChange` in before-plugin triggers `change.setValue`, this saves to history by default, making undo stack's size 1 instead of 0.

Then when popping up this undo item, a redundant `setValue` operation is performed as inverse, this operation contains `{ save: true }`, so it fills undo stack again, which is makes undo stack behaves as alway 'remaining' one sole item.

This screenshot demonstrates the process described above when trying to pop up last undo item:

redo-clear-marked

As as solution, this PR detects history stack size when we tries to update `editor.schema`, setting the `save` args to false for initialization, in this way both issue can be solved.

A side effect I can think of is that we'll now keep the first passed in schema as 'default', this seems to be reasonable. If schema changes afterward, it'll still be recorded into history stack and still undoable.

### CODE REVIEW

File: packages/slate-react/src/plugins/before.js [hunk 1]
```diff
@@ -103,8 +103,14 @@ function BeforePlugin() {
...
     if (value.schema != editor.schema) {
+      // When change on initialization, don't save change into history, making
+      // this schema as default and history clean after initialization ends.
+      const isInit = (
+        value.history.undos.size === 0 &&
+        value.history.redos.size === 0
+      )
       change
-        .setValue({ schema: editor.schema })
+        .setValue({ schema: editor.schema }, { save: !isInit })
```
Comment (ianstormtaylor) [inline packages/slate-react/src/plugins/before.js]: Actually, I think we could just always not save for this one? Since no matter what it's going to continue to get set even if the user does undo it?

Comment (doodlewind) [reply packages/slate-react/src/plugins/before.js]: Fixed!

**Comment by ianstormtaylor** [comment]
Thanks @doodlewind!
