### PR TITLE
Remove `value` from `operation.fromJSON`

### LINKED ISSUE #1439: Operations don't round-trip through JSON
#### Do you want to request a *feature* or report a *bug*?

Report a bug.

#### What's the current behavior?

https://jsfiddle.net/gm13srfv/1/

Open the console and trigger a change (set_selection by clicking in the editor should be enough). You'll see the following error: 

> `Operation.fromJSON` was passed a “set_selection” operation without the required “value” attribute.

#### What's the expected behavior?

I would expect to get an Operation back that could be used like the original Operation.

It looks like the `value` attribute gets stripped in `toJSON`, but Slate tries to parse it back in in `fromJSON`.

I _think_ the value is only used for local undo / redo, it which case I think it should be stripped in `toJSON` and not expected in `fromJSON`. But I wanted to confirm before I send a PR. Either way, it should be consistent.

### PR DESCRIPTION
**Pull request by justinweiss**
Value is only used for local undo / redo, so it shouldn't be serialized along with the rest of the data. This fixes #1439.

### CODE REVIEW

File: packages/slate/src/models/operation.js [hunk 1]
```diff
@@ -124,10 +125,6 @@ class Operation extends Record(DEFAULTS) {
         v = Range.create(v)
       }
 
-      if (key == 'value') {
-        v = Value.create(v)
-      }
-
```
Comment (ianstormtaylor) [inline packages/slate/src/models/operation.js]: Is removing this part required? It looks like the other skipped properties are still present in this section.

Comment (justinweiss) [reply packages/slate/src/models/operation.js]: Ah, I read that as dead code. But I guess it would still run if you specifically passed something for the `value` key.

**Comment by ianstormtaylor** [comment]
Thanks @justinweiss!
