### PR TITLE
fix: automatically inserts an empty text node after inserting an image

### LINKED ISSUE #5597: Cannot add text after creating an image in official Slate image example
**Description**
When you insert an image in the official image example, you cannot insert text after that image

**Steps**
To reproduce the behavior:
1. Go to the official slate image example sandbox: https://www.slatejs.org/examples/images
2. Try to type any text after the picture of the sheep

You can also replicate this bug by deleting all the text and inserting an image, and then trying to add text after that image.

**Expectation**
Upon inserting an image, you should be able to click on the image, press "enter" and have a new line appear after the image. 

**Environment**
- Slate Version: Unsure—whichever is officially hosted on slate docs
- Operating System: MacOS
- Browser: Safari

### PR DESCRIPTION
**Pull request by CaptainCrouton89**
**Description**
Automatically adds an empty text node after inserting an image in the example code for using images in Slate. 

**Issue**
Fixes #5597

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

### CODE REVIEW

**Review by dylans — APPROVED** [review]
Thanks for the fix @CaptainCrouton89

**Review by dylans — CHANGES_REQUESTED** [review]
@CaptainCrouton89  see the quick suggested changes by Prettier. Thanks.

File: site/examples/images.tsx [hunk 1]
```diff
@@ -82,6 +82,10 @@ const insertImage = (editor, url) => {
   const text = { text: '' }
   const image: ImageElement = { type: 'image', url, children: [text] }
   Transforms.insertNodes(editor, image)
+  Transforms.insertNodes(editor, {
+    type: "paragraph",
```
Comment (dylans) [inline site/examples/images.tsx:86]:
```suggestion
    type: 'paragraph',
```

File: site/examples/images.tsx [hunk 2]
```diff
@@ -82,6 +82,10 @@ const insertImage = (editor, url) => {
...
+    children: [{ text: "" }],
```
Comment (dylans) [inline site/examples/images.tsx:87]:
```suggestion
    children: [{ text: '' }],
```

File: site/examples/images.tsx [hunk 3]
```diff
@@ -82,6 +82,10 @@ const insertImage = (editor, url) => {
...
+  });
```
Comment (dylans) [inline site/examples/images.tsx:88]:
```suggestion
  })
```

**Review by dylans — CHANGES_REQUESTED** [review]
suggested changes from prettier

**Review by dylans — APPROVED** [review]

**Comment by CaptainCrouton89** [comment]
Thanks for fixing that! Glad it's making it in :)
