### PR TITLE
fix(at-range): forward deletion now stays with next block.

### LINKED ISSUE #1457: Delete key behaves more like backspace when selected block is empty
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?

When the selection is on an empty block, the delete key behavior is more like backspace.

This causes an odd behavior where the cursor moves to the previous sibling when delete key is pressed instead of staying at the same block. Additionally, delete does not promote the content next sibling block to the current selected block as expected.

http://recordit.co/cBMAOQVAr8

#### What's the expected behavior?

Expected behavior is that delete key always maintains current block selection.

### PR DESCRIPTION
**Pull request by zGrav**
Should fix #1457 .

### CODE REVIEW

File: packages/slate/src/changes/at-range.js [hunk 1]
```diff
@@ -557,7 +557,12 @@ Changes.deleteForwardAtRange = (change, range, n = 1, options = {}) => {
 
   // If the closest is not void, but empty, remove it
   if (block && !block.isVoid && block.isEmpty && document.nodes.size !== 1) {
+    const nextBlock = document.getNextBlock(block.key)
     change.removeNodeByKey(block.key, { normalize })
+    if (nextBlock && nextBlock.key) {
+      change.moveToRangeOf(nextBlock)
+      change.moveOffsetsTo(0, 0)
```
Comment (ianstormtaylor) [inline packages/slate/src/changes/at-range.js]: I think this can be summarized as `moveToStartOf(nextBlock)`

Comment (zGrav) [reply packages/slate/src/changes/at-range.js]: Yup. Pushed, thanks!

**Comment by CameronAckermanSEL** [comment]
@zGrav thanks so much :)
