### PR TITLE
Resolve issues with focus and blur transformations in the DOM

### LINKED ISSUE #297: transforms blur and focus do not work properly
The state transforms blur and focus do not work properly in both firefox and chrome. I uploaded a demo here: https://jsfiddle.net/q2mmegtj/3/

I believe that the problem is that

```
state.transform()
    .focus() // or
    .blur()
    .apply();  
```

transforms the state, but does not do anything in the DOM. Thus, the transforms don't work properly in neither firefox nor chrome.

In Chrome, when the focus is blurred, you can still continue typing:

slate-blur

In firefox, neither blur nor focus have *any* effect:

slate-undo-firefox

I have no idea how to approach this issue. I experimented with DOMElement.focus() and .blur on the contenteditable with little effect. `window.getSelection().removeAllRanges()` has the desired effect but does not work when the next focused element has a range.

### PR DESCRIPTION
**Pull request by arekkas**
Things to note:

1. This won't work in IE / Edge because it uses [`closest()`](http://caniuse.com/#search=closest). However, slate uses `closest()` in several places so I just rolled with it.
2. I have no idea how to write tests for this.
3. I'm not sure if it resolves all issues with focus/blur, but I tested a few cases where it worked (and previously didn't).
4. Previously, `document.activeElement` didn't change. Now, after executing the blur transform, it will be the body element.
5. We can't trust `state.selection` in isLeaf because it might be out of date in environments that are a bit slow. Because it is not possible to get the real steat I added a DOM-based check that detects if our contenteditable is still responsible for handling the selection.

Closes #297 and maybe #418

### CODE REVIEW

**Comment by arekkas** [comment]
Don't merge this just yet, I may have found an issue here

**Comment by arekkas** [comment]
Yes indeed, I think there is an issue when more than one editor is included on the page.

File: src/components/leaf.js [hunk 1]
```diff
@@ -148,17 +145,41 @@ class Leaf extends React.Component {
...
+
+    // If no selection is defined we're probably in a node environment and we can skip the selection magic.
+    if (!window || !window.getSelection) return
+
+    const native = window.getSelection()
+    const parent = ref.closest('[contenteditable]')
+
+    // If the selection is blurred but the native selection has still edges in this leaf,
+    // we need to clean up the ranges and blur the contenteditable.
+    if (selection.isBlurred && (hasAnchor || hasFocus)) {
```
Comment (arekkas) [inline src/components/leaf.js]: The problem is that I thought that `hasAnchor || hasFocus` is being computed by the native selection, but it's computed using the document selection. this obviously yields true multiple times if multiple slate instances exist and then causes the removeallranges thing to remove the selection of the second slate instance.

The idea behind this was that by checking if the current selection is still in the contenteditable although it should be blurred, we blur the selection using the DOM.

File: src/components/leaf.js [hunk 2]
```diff
@@ -148,17 +163,47 @@ class Leaf extends React.Component {
...
+    const parent = ref.closest('[contenteditable]')
+
+    // If the selection is blurred but the DOM selection still focuses this leaf,
+    // we need to clean up the ranges and blur the contenteditable.
+    if (selection.isBlurred && (hasAnchor || hasFocus)) {
+      // We need to make sure that the selection from our state is up-to-date with the native selection.
+      // We can do this by checking if native.anchorNode is a descendant of our contenteditable parent, which is this
+      // slate instance. If it's not, the selection is no longer under this instance's responsibility and not further
+      // action is required.
+      if (!isDescendant(parent, native.anchorNode)) return
```
Comment (ianstormtaylor) [inline src/components/leaf.js]: Could we do this inside `componentDidMount/Update` inside `src/content.js` instead? That way it could be a more generic case, where we only need to check "was it focused before, blurred now, and still have a range inside the `contenteditable`?".

File: src/components/leaf.js [hunk 3]
```diff
@@ -148,17 +163,47 @@ class Leaf extends React.Component {
...
+
+      // Apparently our selection is blurred, but the DOM still has ranges in the nodes we manage. To fix this,
+      // we blur the contenteditable and remove all ranges.
+      native.removeAllRanges()
+      if (parent) parent.blur()
```
Comment (ianstormtaylor) [inline src/components/leaf.js]: Why the need to both `blur()` and `removeAllRanges()`? I would have assumed that either one would do?

**Comment by ianstormtaylor** [comment]
Hey @arekkas thanks for looking into this! The `focus()` treatment for Firefox is a good find. I added comments about the blurring logic for you to check out. Happy to get this merged in once we've sorted a few things!

File: src/components/leaf.js [hunk 4]
```diff
@@ -148,17 +163,47 @@ class Leaf extends React.Component {
     const hasFocus = selection.hasFocusBetween(node, start, end)
     if (!hasAnchor && !hasFocus) return
 
+    // We have a selection to render, so prepare a few things...
+    const ref = ReactDOM.findDOMNode(this)
+    const el = findDeepestNode(ref)
+    const window = getWindow(el)
+
+    // If no selection is defined we're probably in a node environment and we can skip the selection magic.
+    if (!window || !window.getSelection) return
```
Comment (arekkas) [inline src/components/leaf.js]: I think the issue was `ReactDOM.renderToStaticMarkup()` if I recall correctly. I will verify the issue

File: src/components/leaf.js (hunk 3 above)
Comment (arekkas) [inline src/components/leaf.js]: No, that's exactly the point of this PR, it's unfortunately not enough to just removeAllRanges, you also need to blur the contenteditable or otherwise key strokes will be processed by the onInput event in all browsers I tested

File: src/components/leaf.js (hunk 2 above)
Comment (arekkas) [inline src/components/leaf.js]: Sure, I'll give it a try!

**Comment by arekkas** [comment]
Thanks for reviewing @ianstormtaylor , I've added some comments and will work on the things you mentioned today.

File: src/components/leaf.js (hunk 4 above)
Comment (arekkas) [inline src/components/leaf.js]: Nevermind, you're right. This code should not be reachable if window is undefined.

**Comment by arekkas** [comment]
Hey @ianstormtaylor I have resolved the comments you posted. The blur magic now happens in `content.js` and the additional focus call is in `leaf.js`. As I mentioned before, blur and removeAllRanges are required to properly set the DOM.activeElement. I think this should be good to merge now :)

**Comment by arekkas** [comment]
Oh and I tested a couple of cases by hand, they all seem to work.

File: src/components/leaf.js (hunk 3 above)
Comment (ianstormtaylor) [inline src/components/leaf.js]: Gotcha, sounds good! Thanks for figuring that out

**Comment by arekkas** [comment]
By the way, travis failed because of a timeout which apparently happens randomly :)

**Comment by ianstormtaylor** [comment]
Awesome, thank you @arekkas!

I've added a `focus-blur` example that will hopefully be useful to continue ensuring the right behavior, until we figure out better tests for the DOM-level stuff

**Comment by arekkas** [comment]
Awesome, thanks for the merge and the example!
