### PR TITLE
fix issue where inline voids can no longer be selected

### LINKED ISSUE #3518: Cannot focus inline void elements
#### Do you want to request a _feature_ or report a _bug_?

_bug_

#### What's the current behavior?

When arrowing through the text in the mentions example, as soon as a mention is highlighted, focus is lost and user can no longer use arrow keys.

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

The mentions should become highlighted and arrow keys should continue to work.

### PR DESCRIPTION
**Pull request by CameronAckermanSEL**
#### Is this adding or improving a _feature_ or fixing a _bug_?
Bug

#### What's the new behavior?
This fixes #3518 by allowing zero width characters to be considered editable dom targets, thereby alloing `onDOMSelectionChange` to select them.

#### How does this change work?

This adds zero-width characters to the set of editable targets that are considered selectable DOM children of the editor

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
Examples checked:
* Mentions Example
* Editable Voids Example
* Embeds Example
* Checklist example (This defect was introduced accidentally as part of https://github.com/ianstormtaylor/slate/pull/3389)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by CameronAckermanSEL** [comment]
@ryanmitts  you've been poking around with selection recently so maybe you could provide some insight on whether this is a sane change? Appreciate your time if you can, if not, no problem at all :)

File: packages/slate-react/src/plugin/react-editor.ts [hunk 1]
```diff
@@ -174,7 +174,9 @@ export const ReactEditor = {
 
     return (
       targetEl.closest(`[data-slate-editor]`) === editorEl &&
-      (!editable || targetEl.isContentEditable)
+      (!editable ||
+        targetEl.isContentEditable ||
+        !!targetEl.getAttribute('data-slate-zero-width'))
```
Comment (CameronAckermanSEL) [inline packages/slate-react/src/plugin/react-editor.ts:179]: adding slate-zero-width characters here means that onDOMSelectionChange will allow this to be a selectable region. The absence of this code causes the deselect routine to be called in the event handler. 

See: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/editable.tsx#L371

Before this change, hasEditableTarget returns false for inline voids (because they're not `isContentEditable=true`)

**Comment by CameronAckermanSEL** [comment]
Tests:

- Checked selection via keyboard on inline voids (forward and backward)
- Checked selection via keyboard on normal inlines and marks (forward and backward) (found same bugs that are on production)
- Checked selection via keyboard on void blocks (forward and backward) (found same bugs that are on production)
- Checked selection via mouse on inline voids (forward and backward)
- Checked selection via mouse on normal inlines and marks (forward and backward) (same bugs)
- Checked selection via mouse on void blocks (forward and backward) (found same bugs)
- Double checked that embedded inputs, and other editable void nodes could still be edited.
- Double checked selection across editable voids (it behaves oddly but this is not a new behavior)
